from __future__ import annotations

from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from bg.envtools import ENV_KEYS, count_ice_entries, read_env_values_with_bash, shell_single_quote


DEFAULT_DATABASES = """{
  "pilot": {
    "name": "cube",
    "host": "127.0.0.1",
    "username": "cube_user",
    "database": "cube_db",
    "password": "CHANGE_ME"
  },
  "bg": {
    "name": "authd bg",
    "host": "127.0.0.1",
    "username": "bg_user",
    "database": "bg_data",
    "password": "CHANGE_ME"
  }
}"""

DEFAULT_ICE = """[
  {
    "icehost": "127.0.0.1",
    "address": "127.0.0.1:64738",
    "name": "127.0.0.1:64738",
    "virtual_server_id": 1,
    "icewrite": "CHANGE_ME",
    "iceport": 6502,
    "iceread": "CHANGE_ME"
  }
]"""

DEFAULT_PROBE = """[
  {
    "host": "127.0.0.1",
    "username": "mumble",
    "database": "mumble_db",
    "password": "CHANGE_ME",
    "dbport": 5432,
    "dbengine": "postgres"
  }
]"""


class Command(BaseCommand):
    help = "Create/update ~/.env/mumble-bg with backup and preserved values."

    def add_arguments(self, parser):
        parser.add_argument("--target", default="~/.env/mumble-bg", help="Target env file path")

    def handle(self, *args, **options):
        target = Path(options["target"]).expanduser()
        target.parent.mkdir(parents=True, exist_ok=True)

        backup_file: Path | None = None
        current: dict[str, str] = {}
        if target.is_file():
            mtime = int(target.stat().st_mtime)
            backup_file = target.with_name(f"{target.name}.{mtime}")
            backup_file.write_bytes(target.read_bytes())
            try:
                current = read_env_values_with_bash(backup_file, ENV_KEYS)
            except Exception as exc:
                raise CommandError(
                    f"Failed to parse existing env file {backup_file}: {exc}. Backup kept."
                ) from exc

        def cur_or_default(key: str, default: str) -> str:
            val = str(current.get(key, "") or "")
            return val if val else default

        dj_settings = cur_or_default("DJANGO_SETTINGS_MODULE", "bg.settings")
        passphrase = cur_or_default("BG_KEY_PASSPHRASE", "CHANGE_ME")
        bg_bind = cur_or_default("BG_BIND", "")
        psk = cur_or_default("MURMUR_CONTROL_PSK", "CHANGE_ME")
        control_url = cur_or_default("MURMUR_CONTROL_URL", "http://127.0.0.1:18080")
        databases = cur_or_default("DATABASES", DEFAULT_DATABASES)
        ice = cur_or_default("ICE", DEFAULT_ICE)
        probe = cur_or_default("MURMUR_PROBE", DEFAULT_PROBE)
        ice_count = count_ice_entries(ice)

        based_on = backup_file.name if backup_file else "defaults"
        lines: list[str] = [
            "# mumble-bg environment template",
            "# Generated by init_bg_env",
            f"# Based on: {based_on}",
            "# Source this before running BG commands:",
            "#   set -a",
            "#   source ~/.env/mumble-bg",
            "#   set +a",
            "",
            "# Required so python -m django ... can run without --settings",
            f"DJANGO_SETTINGS_MODULE={shell_single_quote(dj_settings)}",
            "",
            "# Required for encrypted private keys generated by generate_bg_keypair",
            f"BG_KEY_PASSPHRASE={shell_single_quote(passphrase)}",
            "",
            "# Optional explicit BG bind override. Leave blank to derive from MURMUR_CONTROL_URL.",
            f"BG_BIND={shell_single_quote(bg_bind)}",
            "",
            "# BG control API shared secret (must match FG)",
            f"MURMUR_CONTROL_PSK={shell_single_quote(psk)}",
            "",
            "# BG control URL advertised to FG/Cube. Also used to derive bind when BG_BIND is blank.",
            f"MURMUR_CONTROL_URL={shell_single_quote(control_url)}",
            "",
            "# BG-owned and pilot-source DB configuration (JSON object)",
            f"DATABASES={shell_single_quote(databases)}",
            "",
            "# ICE endpoint inventory (JSON list)",
            "# IMPORTANT:",
            "# - `icehost` is the ICE endpoint host/IP.",
            "# - `address` is the Mumble server address shown to users and must be an IP or resolvable hostname.",
            "# - `address` without `:port` implies the default Mumble port `64738`.",
            "# - To use a non-default port, set `address` as `host:port`.",
            "# - `name` is the FG/profile title and defaults to `address`.",
            "# - Use `python -m django shell_export KEY VALUE...` for difficult values.",
            "# - Example icesecretwrite value with literal single quotes:",
            "#   \"'CubeiNive'\"",
            f"ICE={shell_single_quote(ice)}",
            "",
        ]
        if ice_count <= 1:
            lines.extend(
                [
                    "# Example second ICE endpoint entry (commented template):",
                    "# ICE='[",
                    "#   {",
                    "#     \"icehost\": \"127.0.0.1\",",
                    "#     \"address\": \"127.0.0.1:64738\",",
                    "#     \"name\": \"127.0.0.1:64738\",",
                    "#     \"virtual_server_id\": 1,",
                    "#     \"icewrite\": \"CHANGE_ME\",",
                    "#     \"iceport\": 6502,",
                    "#     \"iceread\": \"CHANGE_ME\"",
                    "#   },",
                    "#   {",
                    "#     \"icehost\": \"127.0.0.2\",",
                    "#     \"address\": \"127.0.0.2:64739\",",
                    "#     \"name\": \"127.0.0.2:64739\",",
                    "#     \"virtual_server_id\": 2,",
                    "#     \"icewrite\": \"CHANGE_ME_2\",",
                    "#     \"iceport\": 6502,",
                    "#     \"iceread\": \"CHANGE_ME_2\"",
                    "#   }",
                    "# ]'",
                    "",
                ]
            )
        lines.extend(
            [
                "# Optional Murmur SQL probe endpoints (JSON list)",
                f"MURMUR_PROBE={shell_single_quote(probe)}",
                "",
            ]
        )

        target.write_text("\n".join(lines), encoding="utf-8")
        target.chmod(0o600)
        self.stdout.write(f"Updated template: {target}")
        if backup_file:
            self.stdout.write(f"Backup created: {backup_file}")
        self.stdout.write("Source it with:")
        self.stdout.write(f"  set -a && source {target} && set +a")
