# Generated by Django 4.2.28 on 2026-02-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mumbleuser',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
