# Generated by Django 4.2.29 on 2026-03-07 12:14

from django.db import migrations, models
import django.db.models.deletion


def copy_last_connected_to_last_authenticated(apps, schema_editor):
    MumbleUser = apps.get_model('mumble', 'MumbleUser')
    MumbleUser.objects.filter(
        last_connected__isnull=False,
        last_authenticated__isnull=True,
    ).update(last_authenticated=models.F('last_connected'))


class Migration(migrations.Migration):

    dependencies = [
        ('mumble', '0007_alter_mumbleuser_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='mumbleuser',
            name='last_authenticated',
            field=models.DateTimeField(blank=True, help_text='Last successful Cube authenticator callback timestamp', null=True),
        ),
        migrations.AddField(
            model_name='mumbleuser',
            name='last_disconnected',
            field=models.DateTimeField(blank=True, help_text='Last confirmed Murmur disconnect timestamp', null=True),
        ),
        migrations.AddField(
            model_name='mumbleuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time Murmur Pulse observed this account online', null=True),
        ),
        migrations.AddField(
            model_name='mumbleuser',
            name='last_spoke',
            field=models.DateTimeField(blank=True, help_text='Last time Murmur reported voice activity for this account', null=True),
        ),
        migrations.RunPython(
            copy_last_connected_to_last_authenticated,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='mumbleuser',
            name='last_connected',
            field=models.DateTimeField(blank=True, help_text='Last confirmed Murmur connection timestamp', null=True),
        ),
        migrations.CreateModel(
            name='MumbleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.PositiveIntegerField()),
                ('mumble_userid', models.IntegerField(blank=True, help_text='Murmur registered-user ID observed for this live session, if any.', null=True)),
                ('username', models.CharField(max_length=255)),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('cert_hash', models.CharField(blank=True, default='', max_length=255)),
                ('tcponly', models.BooleanField(default=False)),
                ('mute', models.BooleanField(default=False)),
                ('deaf', models.BooleanField(default=False)),
                ('suppress', models.BooleanField(default=False)),
                ('priority_speaker', models.BooleanField(default=False)),
                ('self_mute', models.BooleanField(default=False)),
                ('self_deaf', models.BooleanField(default=False)),
                ('recording', models.BooleanField(default=False)),
                ('onlinesecs', models.PositiveIntegerField(default=0)),
                ('idlesecs', models.PositiveIntegerField(default=0)),
                ('connected_at', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('last_state', models.DateTimeField()),
                ('last_spoke', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mumble_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_sessions', to='mumble.mumbleuser')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_sessions', to='mumble.mumbleserver')),
            ],
            options={
                'db_table': 'mumble_mumblesession',
                'ordering': ['-connected_at', '-id'],
                'indexes': [models.Index(fields=['server', 'is_active'], name='mumble_mumb_server__6ed47e_idx'), models.Index(fields=['mumble_user', 'is_active'], name='mumble_mumb_mumble__8ffc31_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mumblesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('server', 'session_id'), name='mumble_session_unique_active_session'),
        ),
    ]
