# Generated by Django 4.2.29 on 2026-03-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mumble', '0008_mumbleuser_last_authenticated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mumblesession',
            options={'ordering': ['-connected_at', '-id'], 'permissions': [('view_mumble_presence', 'Can view current Mumble presence'), ('view_mumble_presence_history', 'Can view Mumble presence history')]},
        ),
    ]
