#!/usr/bin/env bash
set -euo pipefail

target="${1:-$HOME/.env/mumble-bg}"

if [[ -e "$target" ]]; then
  echo "Refusing to overwrite existing file: $target"
  echo "Move/delete it first, or pass a different target path."
  exit 1
fi

mkdir -p "$(dirname "$target")"
cat > "$target" <<'EOF'
# mumble-bg environment template
# Source this before running BG commands:
#   set -a
#   source ~/.env/mumble-bg
#   set +a

# Required so `python -m django ...` can run without --settings
DJANGO_SETTINGS_MODULE=bg.settings

# Required for encrypted private keys generated by generate_bg_keypair
BG_KEY_PASSPHRASE='CHANGE_ME'

# BG control API shared secret (must match FG)
MURMUR_CONTROL_PSK='CHANGE_ME'

# BG runtime bind (example for local test/dev)
MURMUR_CONTROL_URL='http://127.0.0.1:18080'

# BG-owned and pilot-source DB configuration (JSON object)
DATABASES='{
  "pilot": {
    "name": "cube",
    "host": "127.0.0.1",
    "username": "cube_user",
    "database": "cube_db",
    "password": "CHANGE_ME"
  },
  "bg": {
    "name": "authd bg",
    "host": "127.0.0.1",
    "username": "bg_user",
    "database": "bg_data",
    "password": "CHANGE_ME"
  }
}'

# ICE endpoint inventory (JSON list)
# IMPORTANT:
# - Use shell_export.sh when values contain difficult characters.
# - Example icesecretwrite value that includes literal single quotes:
#   "'CubeiNive'"
ICE='[
  {
    "host": "127.0.0.1",
    "virtual_server_id": 1,
    "icewrite": "CHANGE_ME",
    "iceport": 6502,
    "iceread": "CHANGE_ME"
  }
]'

# Optional Murmur SQL probe endpoints (JSON list)
MURMUR_PROBE='[
  {
    "host": "127.0.0.1",
    "username": "mumble",
    "database": "mumble_db",
    "password": "CHANGE_ME",
    "dbport": 5432,
    "dbengine": "postgres"
  }
]'
EOF

chmod 600 "$target"
echo "Created template: $target"
echo "Next:"
echo "  1) edit values marked CHANGE_ME"
echo "  2) source it:"
echo "     set -a && source $target && set +a"
