#!/usr/bin/env bash
set -euo pipefail

target="${1:-$HOME/.env/mumble-bg}"
script_name="$(basename "$0")"
backup_file=""

sq() {
  # Emit a shell-safe single-quoted literal.
  # Example: abc'def -> 'abc'"'"'def'
  printf "'%s'" "${1//\'/\'\"\'\"\'}"
}

if [[ -f "$target" ]]; then
  mtime="$(date -r "$target" +%Y%m%d%H%M%S)"
  backup_file="${target}.${mtime}"
  cp -a "$target" "$backup_file"
fi

mkdir -p "$(dirname "$target")"

declare -A current=()
# BG_KEY_PASSPHRASE is a deprecated alias; we read it for migration but do not emit it.
vars=(DJANGO_SETTINGS_MODULE BG_PKI_PASSPHRASE BG_KEY_PASSPHRASE BG_BIND BG_DBMS BG_PSK MURMUR_CONTROL_URL DATABASES ICE MURMUR_PROBE)

if [[ -n "$backup_file" ]]; then
  extracted="$(mktemp)"
  if ! bash -c '
    set -euo pipefail
    source_file="$1"
    out_file="$2"
    shift 2
    set -a
    # shellcheck disable=SC1090
    source "$source_file"
    set +a
    : > "$out_file"
    for k in "$@"; do
      printf "%s\0%s\0" "$k" "${!k-}" >> "$out_file"
    done
  ' _ "$backup_file" "$extracted" "${vars[@]}"; then
    rm -f "$extracted"
    echo "Failed to parse existing env file: $backup_file" >&2
    echo "Backup is preserved. Fix file syntax and rerun." >&2
    exit 1
  fi

  while IFS= read -r -d '' key && IFS= read -r -d '' value; do
    current["$key"]="$value"
  done < "$extracted"
  rm -f "$extracted"
fi

val_or_default() {
  local key="$1"
  local def="$2"
  if [[ -n "${current[$key]+x}" && -n "${current[$key]}" ]]; then
    printf "%s" "${current[$key]}"
  else
    printf "%s" "$def"
  fi
}

dj_settings="$(val_or_default DJANGO_SETTINGS_MODULE "bg.settings")"
bg_passphrase="$(val_or_default BG_PKI_PASSPHRASE "$(val_or_default BG_KEY_PASSPHRASE "CHANGE_ME")")"
bg_bind="$(val_or_default BG_BIND "")"
control_psk="$(val_or_default BG_PSK "CHANGE_ME")"
control_url="$(val_or_default MURMUR_CONTROL_URL "http://127.0.0.1:18080")"
databases_json="$(val_or_default BG_DBMS "$(val_or_default DATABASES '{
  "name": "authd bg",
  "host": "127.0.0.1",
  "username": "bg_username",
  "database": "bg_database",
  "password": "bg_secretPassword"
}')")"
ice_json="$(val_or_default ICE '[
  {
    "icehost": "localhost",
    "address": "voice.yourhost.tld:64738",
    "name": "Mumble Server Name in Dialogs",
    "virtual_server_id": 1,
    "icewrite": "bg_iceWriteSecret",
    "iceport": 6502,
    "iceread": "bg_iceReadSecret"
  }
]')"
probe_json="$(val_or_default MURMUR_PROBE '[
  {
    "host": "127.0.0.1",
    "username": "mumble",
    "database": "mumble_db",
    "password": "CHANGE_ME",
    "dbport": 5432,
    "dbengine": "postgres"
  }
]')"

ice_count="$(python3 - "$ice_json" <<'PY'
import json
import sys
raw = sys.argv[1]
try:
    value = json.loads(raw)
    if isinstance(value, list):
        print(len(value))
    else:
        print(0)
except Exception:
    print(0)
PY
)"

if [[ -n "$backup_file" ]]; then
  based_on="$(basename "$backup_file")"
else
  based_on="defaults"
fi

cat > "$target" <<EOF
# mumble-bg environment template
# Generated by ${script_name}
# Based on: ${based_on}
# Source this before running BG commands:
#   set -a
#   source ~/.env/mumble-bg
#   set +a

# Required so python -m django ... can run without --settings
DJANGO_SETTINGS_MODULE=$(sq "$dj_settings")

# Required for encrypted private keys generated by generate_bg_keypair
BG_PKI_PASSPHRASE=$(sq "$bg_passphrase")

# Optional explicit BG bind override. Leave blank to derive from MURMUR_CONTROL_URL.
BG_BIND=$(sq "$bg_bind")

# FG/BG control API shared secret (must match FG)
BG_PSK=$(sq "$control_psk")

# BG control URL advertised to FG/Cube. Also used to derive bind when BG_BIND is blank.
MURMUR_CONTROL_URL=$(sq "$control_url")

# BG-owned DB configuration (JSON object)
# Flat object is preferred. Legacy nested {"bg": {...}} is still accepted.
BG_DBMS=$(sq "$databases_json")

# ICE endpoint inventory (JSON list)
# IMPORTANT:
# - icehost is the ICE endpoint host/IP.
# - address is the Mumble server address shown to users and must be an IP or resolvable hostname.
# - address without :port implies the default Mumble port 64738.
# - To use a non-default port, set address as host:port.
# - name is the FG/profile title and defaults to address.
# - Use shell_export.sh when values contain difficult characters.
# - Example icesecretwrite value that includes literal single quotes:
#   "'CubeiNive'"
ICE=$(sq "$ice_json")

EOF

if [[ "$ice_count" -le 1 ]]; then
  cat >> "$target" <<'EOF'
# Example second ICE endpoint entry (commented template):
# ICE='[
#   {
#     "icehost": "localhost",
#     "address": "voice.yourhost.tld:64738",
#     "name": "Mumble Server Name in Dialogs",
#     "virtual_server_id": 1,
#     "icewrite": "bg_iceWriteSecret",
#     "iceport": 6502,
#     "iceread": "bg_iceReadSecret"
#   },
#   {
#     "icehost": "localhost",
#     "address": "voice.yourhost.tld:64739",
#     "name": "Second Mumble Server Name in Dialogs",
#     "virtual_server_id": 2,
#     "icewrite": "bg_iceWriteSecret_2",
#     "iceport": 6502,
#     "iceread": "bg_iceReadSecret_2"
#   }
# ]'
EOF
fi

cat >> "$target" <<EOF

# Optional Murmur SQL probe endpoints (JSON list)
MURMUR_PROBE=$(sq "$probe_json")
EOF

chmod 600 "$target"
echo "Updated template: $target"
if [[ -n "$backup_file" ]]; then
  echo "Backup created: $backup_file"
fi
echo "Source it with:"
echo "  set -a && source $target && set +a"
