# Generated by Django 5.0.14 on 2026-03-23 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.BigIntegerField(help_text='EVE Online ID (alliance, corporation, or character).', unique=True)),
                ('entity_type', models.CharField(choices=[('alliance', 'Alliance'), ('corporation', 'Corporation'), ('pilot', 'Pilot')], help_text='Deducible from ID range but kept for query convenience.', max_length=16)),
                ('deny', models.BooleanField(default=False, help_text='False = permit (default). True = deny access.')),
                ('acl_admin', models.BooleanField(default=False, help_text='Pilot-only Murmur admin marker. Ignored for alliance/corporation rules.')),
                ('note', models.TextField(blank=True, default='', help_text='Admin notes (e.g. reason for denial, ticket reference).')),
                ('created_by', models.CharField(blank=True, default='', help_text='Who added this rule.', max_length=255)),
                ('synced_at', models.DateTimeField(blank=True, help_text='When this rule was last received from FG via control channel.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bg_access_rule',
                'ordering': ['entity_type', 'entity_id'],
            },
        ),
        migrations.CreateModel(
            name='AccessRuleSyncAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(default='sync', help_text='Operation that produced this record', max_length=16)),
                ('state_before', models.JSONField(blank=True, default=dict)),
                ('state_after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bg_access_rule_audit',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BgAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('acl_sync', 'ACL Sync'), ('pilot_create', 'Pilot Created'), ('pilot_disable', 'Pilot Disabled'), ('pilot_enable', 'Pilot Enabled'), ('pilot_pwreset', 'Pilot Password Reset'), ('pilot_login', 'Pilot Authenticated'), ('pilot_display_name_update', 'Pilot Display Name Updated')], max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('server_name', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bg_audit',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ControlChannelKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='fg_bg', max_length=64, unique=True)),
                ('shared_secret', models.CharField(blank=True, default=None, help_text='FG/BG control channel PSK. If NULL, control falls back to env bootstrap secret.', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'control_channel_key',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EveObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.BigIntegerField(help_text='EVE object ID (pilot, corporation, alliance).', unique=True)),
                ('type', models.CharField(choices=[('alliance', 'Alliance'), ('corporation', 'Corporation'), ('pilot', 'Pilot')], max_length=16)),
                ('category', models.CharField(choices=[('alliance', 'Alliance'), ('corporation', 'Corporation'), ('character', 'Character')], max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('ticker', models.CharField(blank=True, default='', max_length=32)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bg_eve_object',
                'ordering': ['type', 'entity_id'],
            },
        ),
        migrations.CreateModel(
            name='MumbleServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g. "Main Fleet Comms")', max_length=255)),
                ('address', models.CharField(help_text='User-facing connection string (e.g. mumble.example.com:64738)', max_length=255)),
                ('ice_host', models.CharField(help_text='ICE endpoint hostname', max_length=255)),
                ('ice_port', models.PositiveIntegerField(default=6502, help_text='ICE endpoint port')),
                ('ice_secret', models.CharField(blank=True, default=None, help_text='ICE write secret (leave blank if none)', max_length=255, null=True)),
                ('virtual_server_id', models.PositiveIntegerField(blank=True, help_text='Target Murmur virtual server ID on this ICE endpoint. Leave blank only if the endpoint hosts a single booted server.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ordering on the profile page (lower = first)')),
            ],
            options={
                'db_table': 'mumble_server',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MumbleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.PositiveIntegerField()),
                ('mumble_userid', models.IntegerField(blank=True, help_text='Murmur registered-user ID observed for this live session, if any.', null=True)),
                ('username', models.CharField(max_length=255)),
                ('channel_id', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('cert_hash', models.CharField(blank=True, default='', max_length=255)),
                ('tcponly', models.BooleanField(default=False)),
                ('mute', models.BooleanField(default=False)),
                ('deaf', models.BooleanField(default=False)),
                ('suppress', models.BooleanField(default=False)),
                ('priority_speaker', models.BooleanField(default=False)),
                ('self_mute', models.BooleanField(default=False)),
                ('self_deaf', models.BooleanField(default=False)),
                ('recording', models.BooleanField(default=False)),
                ('onlinesecs', models.PositiveIntegerField(default=0)),
                ('idlesecs', models.PositiveIntegerField(default=0)),
                ('connected_at', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('last_state', models.DateTimeField()),
                ('last_spoke', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mumble_session',
                'ordering': ['-connected_at', '-id'],
                'permissions': [('view_mumble_presence', 'Can view current Mumble presence'), ('view_mumble_presence_history', 'Can view Mumble presence history')],
            },
        ),
        migrations.CreateModel(
            name='MumbleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evepilot_id', models.BigIntegerField(blank=True, help_text='Pilot character ID tracked in the FG/BG contract.', null=True)),
                ('corporation_id', models.BigIntegerField(blank=True, help_text='Pilot corporation ID tracked in the FG/BG contract.', null=True)),
                ('alliance_id', models.BigIntegerField(blank=True, help_text='Pilot alliance ID tracked in the FG/BG contract.', null=True)),
                ('mumble_userid', models.PositiveIntegerField(blank=True, help_text='Server-assigned Murmur user ID for this registration.', null=True)),
                ('username', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('pwhash', models.CharField(max_length=255)),
                ('hashfn', models.CharField(default='murmur-pbkdf2-sha384', max_length=32)),
                ('pw_salt', models.CharField(blank=True, default='', max_length=64)),
                ('kdf_iterations', models.PositiveIntegerField(blank=True, null=True)),
                ('certhash', models.CharField(blank=True, default='', help_text='Client certificate hash (updated on each connection)', max_length=255)),
                ('groups', models.TextField(blank=True, default='')),
                ('last_authenticated', models.DateTimeField(blank=True, help_text='Last successful mumble-bg authenticator callback timestamp', null=True)),
                ('last_connected', models.DateTimeField(blank=True, help_text='Last confirmed Murmur connection timestamp', null=True)),
                ('last_disconnected', models.DateTimeField(blank=True, help_text='Last confirmed Murmur disconnect timestamp', null=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time Murmur Pulse observed this account online', null=True)),
                ('last_spoke', models.DateTimeField(blank=True, help_text='Last time Murmur reported voice activity for this account', null=True)),
                ('is_mumble_admin', models.BooleanField(default=False, help_text='Grant Mumble server admin permissions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mumble_user',
                'permissions': [('manage_mumble_admin', 'Can manage Mumble admin grants')],
            },
        ),
        migrations.CreateModel(
            name='PilotAccountCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkid', models.BigIntegerField(help_text='Stable FG/BG account identity key.', unique=True)),
                ('account_username', models.CharField(blank=True, default='', help_text='Cube login username from the latest FG snapshot.', max_length=255)),
                ('pilot_data_hash', models.CharField(blank=True, db_index=True, default='', help_text='Hash of pilot snapshot payload for this account (md5 placeholder).', max_length=64)),
                ('display_name', models.CharField(blank=True, default='', help_text='Computed display name from the latest FG snapshot.', max_length=255)),
                ('main_character_id', models.BigIntegerField(blank=True, help_text='Main character ID from the latest FG snapshot.', null=True)),
                ('main_character_name', models.CharField(blank=True, default='', help_text='Main character name from the latest FG snapshot.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bg_pilot_account',
                'ordering': ['pkid'],
            },
        ),
        migrations.CreateModel(
            name='PilotCharacterCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(unique=True)),
                ('character_name', models.CharField(max_length=255)),
                ('corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('corporation_name', models.CharField(blank=True, default='', max_length=255)),
                ('alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('alliance_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bg_pilot_character',
                'ordering': ['account__pkid', '-is_main', 'character_name', 'character_id'],
            },
        ),
        migrations.CreateModel(
            name='PilotSnapshotSyncAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(default='sync', help_text='Operation that produced this record', max_length=16)),
                ('summary_before', models.JSONField(blank=True, default=dict)),
                ('summary_after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bg_pilot_snapshot_audit',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='accessrule',
            constraint=models.CheckConstraint(check=models.Q(('acl_admin', False), ('entity_type', 'pilot'), _connector='OR'), name='bg_access_rule_acl_admin_pilot_only'),
        ),
        migrations.AddField(
            model_name='mumblesession',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murmur_sessions', to='state.mumbleserver'),
        ),
        migrations.AddField(
            model_name='mumbleuser',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murmur_registrations', to='state.mumbleserver'),
        ),
        migrations.AddField(
            model_name='mumbleuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murmur_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mumblesession',
            name='mumble_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='murmur_sessions', to='state.mumbleuser'),
        ),
        migrations.AddField(
            model_name='pilotcharactercache',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='state.pilotaccountcache'),
        ),
        migrations.AddConstraint(
            model_name='mumbleuser',
            constraint=models.UniqueConstraint(condition=models.Q(('mumble_userid__isnull', False)), fields=('server', 'mumble_userid'), name='mumble_user_unique_server_userid'),
        ),
        migrations.AlterUniqueTogether(
            name='mumbleuser',
            unique_together={('user', 'server')},
        ),
        migrations.AddIndex(
            model_name='mumblesession',
            index=models.Index(fields=['server', 'is_active'], name='mumble_sess_server__0310c1_idx'),
        ),
        migrations.AddIndex(
            model_name='mumblesession',
            index=models.Index(fields=['mumble_user', 'is_active'], name='mumble_sess_mumble__5be72e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mumblesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('server', 'session_id'), name='mumble_session_unique_active_session'),
        ),
        migrations.AddConstraint(
            model_name='pilotcharactercache',
            constraint=models.UniqueConstraint(fields=('account', 'character_id'), name='bg_pilot_character_unique_account_character'),
        ),
    ]
