# Generated by Django 5.0.14 on 2026-03-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0000_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotAccountCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkid', models.BigIntegerField(help_text='Stable FG/BG account identity key.', unique=True)),
                ('main_character_id', models.BigIntegerField(blank=True, help_text='Main character ID from the latest FG snapshot.', null=True)),
                ('main_character_name', models.CharField(blank=True, default='', help_text='Main character name from the latest FG snapshot.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bg_pilot_account',
                'ordering': ['pkid'],
            },
        ),
        migrations.CreateModel(
            name='PilotSnapshotSyncAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(default='sync', help_text='Operation that produced this record', max_length=16)),
                ('summary_before', models.JSONField(blank=True, default=dict)),
                ('summary_after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bg_pilot_snapshot_audit',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PilotCharacterCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(unique=True)),
                ('character_name', models.CharField(max_length=255)),
                ('corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('corporation_name', models.CharField(blank=True, default='', max_length=255)),
                ('alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('alliance_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='state.pilotaccountcache')),
            ],
            options={
                'db_table': 'bg_pilot_character',
                'ordering': ['account__pkid', '-is_main', 'character_name', 'character_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pilotcharactercache',
            constraint=models.UniqueConstraint(fields=('account', 'character_id'), name='bg_pilot_character_unique_account_character'),
        ),
    ]
