# Generated by Django 5.0.14 on 2026-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_alter_bgaudit_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgaudit',
            name='action',
            field=models.CharField(choices=[('acl_sync', 'ACL Sync'), ('pilot_create', 'Pilot Created'), ('pilot_disable', 'Pilot Disabled'), ('pilot_enable', 'Pilot Enabled'), ('pilot_pwreset', 'Pilot Password Reset'), ('pilot_login', 'Pilot Authenticated'), ('pilot_display_name_update', 'Pilot Display Name Updated')], max_length=64),
        ),
    ]
