# Generated by Django 4.2.29 on 2026-05-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_mumble_user_temporary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgaudit',
            name='action',
            field=models.CharField(choices=[('acl_sync', 'ACL Sync'), ('pilot_create', 'Pilot Created'), ('pilot_disable', 'Pilot Disabled'), ('pilot_enable', 'Pilot Enabled'), ('pilot_pwreset', 'Pilot Password Reset'), ('pilot_login', 'Pilot Authenticated'), ('pilot_display_name_update', 'Pilot Display Name Updated'), ('pilot_certhash_clear', 'Pilot Certhash Cleared')], max_length=64),
        ),
    ]
