# Generated by Django 4.2.29 on 2026-07-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_mumble_server_shitspeak_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='mumbleserver',
            name='endpoints',
            field=models.TextField(blank=True, default='', help_text='ShitSpeak driver: newline-separated host:port connect endpoints, one per cluster region (e.g. us-voice.undock.wtf:64738). The user-facing region selector is built from these; when empty the profile panel falls back to `address`.'),
        ),
    ]
